effects_dict = {
    'awful              ': "-> MIA's Paper Planes with the grapefruit sound",
    'bf_rockets         ': '-> "Watch those wrist rockets!" (Star Wars BF 2 on PS2)',
    'bf_simulation      ': '-> "Just like the simulations" (Star Wars BF 2 on PS2)',
    'jp_double          ': '-> "Double Jeopardy" ringer',
    'jp_final           ': '-> "Final Jeopardy" ringer',
    'jp_intro           ': '-> Jeopardy intro song',
    'jp_time            ': '-> Jeopardy "Time Is Up" ringer',
    'law                ': '-> "DUN DUN" from Law and Order',
    'nfl                ': '-> NFL on FOX Intro (LOUD)',
    'sa_approach        ': '-> Announcer: "Approach!" (SSBU)',
    'sa_choose          ': '-> Announcer: "Choose your fighter!" (SSBU)',
    'sa_complete        ': '-> Announcer: "Complete!" (SSBU)',
    'sa_congratulations ': '-> Announcer: "Congratulations!" (SSBU)',
    'sa_continue        ': '-> Announcer: "Continue?" (SSBU)',
    'sa_countdown       ': '-> Announcer: "5... 4... 3... 2... 1..." (SSBU)',
    'sa_defeat          ': '-> Announcer: "Defeat!" (SSBU)',
    'sa_defeated        ': '-> Announcer: "Defeated!" (SSBU)',
    'sa_failure         ': '-> Announcer: "FAILURE!" (SSBU)',
    'sa_game            ': '-> Announcer: "Game!" (SSBU)',
    'sa_go              ': '-> Announcer: "Go!" (SSBU)',
    'sa_new_record      ': '-> Announcer: "New record!" (SSBU)',
    'sa_no_contest      ': '-> Announcer: "No contest." (SSBU)',
    'sa_ready           ': '-> Announcer: "Ready?" (SSBU)',
    'sa_sudden_death    ': '-> Announcer: "Sudden Death!" (SSBU)',
    'sa_time            ': '-> Announcer: "Time!" (SSBU)',
    'sa_victory         ': '-> Announcer: "Victory!" (SSBU)',
    'sa_wow             ': '-> Announcer: "Wow! Incredible!" (SSBU)',
}